#!/usr/bin/env bash

case "$1" in
    1)
    sed -i 's_THEME=.*_THEME="aetherLight"_' ~/.config/aether/aether-corevar
    ;;
    2)
    sed -i 's_THEME=.*_THEME="aetherDark"_' ~/.config/aether/aether-corevar
    ;;
    *)
    sed -i 's_THEME=.*_THEME="aetherLight"_' ~/.config/aether/aether-corevar
    ;;
esac

~/.config/aether/kill-ui &> /dev/null
~/.config/aether/startup &> /dev/null
